
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_DEV'] %>
  username: <%= ENV['DATABASE_USER_DEV'] %>
  password: <%= ENV['DATABASE_PASS_DEV'] %>
test:
  <<: *default
  database: <%= ENV['DATABASE_TEST'] %>
  username: <%= ENV['DATABASE_USER_TEST'] %>
  password: <%= ENV['DATABASE_PASS_TEST'] %>
production:
  <<: *default
  database: <%= ENV['DATABASE_PROD'] %>
  username: <%= ENV['DATABASE_USER_PROD'] %>
  password: <%= ENV['DATABASE_PASS_PROD'] %>
